### PR TITLE
dbseeder -> ugsdbseeder

### PR DESCRIPTION
**Pull request by stdavis**
To prevent import collisions between forklift pallets from other
projects.

### CODE REVIEW

**Comment by stdavis** [comment]
@steveoh: Would you mind reviewing this?

**Comment by steveoh** [comment]
this looks good other than

```
76 tests run in 1.1 seconds.
24 errors (52 tests passed)
```

**Comment by stdavis** [comment]
OK. I've fixed the unit tests. @steveoh Do you want to look at it anymore or am I good to merge?

**Comment by steveoh** [comment]
LGTM. Too bad travis failed.

**Pull request merged**
