### PR TITLE
Dictionary for populating `ParamGroup`

### PR DESCRIPTION
**Pull request by inkenbrandt**
Dictionary compiled from SDWIS, NWIS, SRS, and WQX to populate `ParamGroup` field in Results table.  Would work well to replace https://github.com/agrc/ugs-db/blob/master/src/dbseeder/services.py#L255-264, although the functions that call the current lists would need to be changed to use a dictionary instead.  I could break this into separate group lists as well if that would work better.

### CODE REVIEW

**Comment by steveoh** [comment]
This is not going to work. The file is too big. Can you tell me how you created it so I can come up with another method for working with these values?

**Comment by inkenbrandt** [comment]
Yes! https://github.com/inkenbrandt/ParamGroup/blob/master/Untitled.ipynb

**Comment by inkenbrandt** [comment]
I can provide more when I am in the office again.

**Comment by inkenbrandt** [comment]
Most of the matches come from the existing lists that you had in [dbseeder](https://github.com/agrc/ugs-db/blob/master/src/dbseeder/services.py#L255-264)  and in the table [`PARAM_MATCH`](https://raw.githubusercontent.com/inkenbrandt/ParamGroup/master/PARAM_MATCH.txt).  There is a column in the `PARAM_MATCH` table named `SDWIS_NAME` that can be used to find the  `parameter_group_nm` (aka the `ParamGroup`)

**Comment by inkenbrandt** [comment]
I could make one dictionary for each `ParamGroup`, which would make them more manageable.

**Pull request closed without merging**
