### PR TITLE
Normalize stationtype

### LINKED ISSUE #5: Populate DataSource values
The database is seeded from several data sets (WQP, SDWIS, UGS, UDOGM).  The field in the `results` table includes the field `DataSource` whose values should be populated by the acronym of the agency that collected that row of data (i.e. based on the source data set). Values are intuitive and are as follows:  
* [x] WQP = WQP
* [x] SDWIS = SDWIS
* [x] DOGM = UDOGM

UGS has datasource pre-populatied
_DOGM_ has datasource pre-populated on stations only.

### PR DESCRIPTION
**Pull request by stdavis**
I believe that this closes #5 in addition to #12.

### CODE REVIEW

**Comment by steveoh** [comment]
Will you squash the :warning: commit

**Comment by stdavis** [comment]
Done

**Comment by stdavis** [comment]
This is looking pretty good to me. Could probably do better with status messages but it's loading data fairly quickly now.

The problem is that I had to combine your closed PR and the open PR to get it to work. Here's what I'm using: https://gist.github.com/stdavis/d9142c4ea9b01b6420bd

So we'll either need to get it worked out in query-csv repo or just roll our own. There's not much to it and we may be able to optimize it even further to our specific use case.

I could also refactor the `measure_time` method (which was super useful) to a separate module. We may even want to push it to agrc.python.

**Comment by stdavis** [comment]
Of course it will also need a rebase before merging also...

**Comment by stdavis** [comment]
We also may want to think about deleting `temp.sqlite3` in between loading each csv file. Mine is already up to 1GB after loading stations and three result files.

**Comment by stdavis** [comment]
@steveoh I think that we are ready to look at merging this PR.

**Comment by steveoh** [comment]
i would recommend rewording the first commit to something about datasources since it's not bumping querycsv.
I also recommend putting the horse and the text about the index on the same line so we can read what perf upgrade you made.
My last recommendation would be to fixup [this commit](https://github.com/agrc/ugs-db/commit/cb592b1d89df73e4a01fa77614c3a827739d507e) since that isn't very important for the commit history.

After you comment/implement these recommendations I'll look over the codes.

but :+1: so far. This is a great improvement and we should start to think about having @inkenbrandt run this version of code and comment on the output.

**Comment by stdavis** [comment]
OK. I rebased again using your suggestions.

**Pull request merged**
